spring:
  profiles:
    active: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT}